language: c

dist: trusty

cache: ccache

compiler:
  - gcc

before_install:
  - cat /etc/apt/sources.list

addons:
  apt:
    packages:
      - valgrind
      - lcov
      - swig/trusty-backports

script:
  - make
  - make test
  - make NightlyCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
