language: c

dist: trusty

cache: ccache

compiler:
  - gcc

addons:
  apt:
    packages:
      - valgrind
      - lcov
      - swig3.0/trusty-backports

script:
  - make
  - make test
  - make NightlyCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
